#
#  EntityManager Configuration 3.4.2
#  http://dev.bukkit.org/server-mods/entitymanager/pages/configuration/
#####

#
#   General settings for EntityManager
###
EntityManager:
  Login-MOTD: true
  Send-Alerts: true
  Metrics: true
  Logging: true
  TooManyDrops:
    Kick: true

#
# Put the names of the worlds you want the plugin to work in
# Worlds not in this list will be completely ignored
### 
World:
  Worldname:
  - world
  - world_nether 
  - world_end

#
# Settings for EXP drops and Enchanting
# You can disable enchanting to require permissions to enchant
# You can disable experience so exp orbs never drop
###
Disable:
  Experience: false
  Enchanting: false

#
# Settings for EntityManager blocking 
###
block:
  Actions:
    zombie-door-break: false
    ender-pickup: true
    pvp: false
    mob-damage: false
    fishing: false
    arrows: false

#
# Block the dispense of the item completely
# Add items to the blacklist and they won't dispense either
###
  Dispense:
    SpawnerEggs: true
    ChickenEggs: true
    FireBalls: true
    XpBottles: true
    Potions: true
    Items:
    - 7
    - 57

#
# Block players from throwing the below items
# If true, player needs to permission to use the below items
###

  Throw:
    XpBottles: true
    FireCharges: true
    ChickenEggs: false
    EnderPearls: false
    EnderEyes: false
    Potions: false

#
# Block Entities from being placing
###
  Entities:
    Boats: false
    Minecarts: false
    Paintings: false

#
# Control the dropping of items in:
# Gamemodes, on death, when a block is broken
# You can make blacklisted items that are blocked from players without permission
###
  ItemDrop:
    Creative-mode: true
    Survival-mode: false
    On-Death: false
    Block-destroy: false
    Blacklisted-items:
    - 57
#
# Block fire from igniting portals
###
  Creation-of:
    portals: false

#
# Used when a player uses an monster egg that isnt blocked
# Uses vault to charge them per use , if vault isnt installed, economy doesn't matter
###
Economy:
  charge:
    monster: 15
    animal: 5
    npc: 10

#
# Disabling an egg makes the egg be blocked unless:
# The player has permission for that egg
###
disabled:
  eggs:
    creeper: true
    skeleton: true
    spider: true
    zombie: true
    slime: true
    ghast: true
    pigman: true
    enderman: true
    cavespider: true
    silverfish: true
    blaze: true
    magmacube: true
    pig: false
    sheep: false
    cow: false
    chicken: false
    squid: true
    wolf: false
    mooshroom: false
    ocelot: false
    villager: true

#
# Disabling an mob makes the mob completely blocked from the world
# -Remember all aspects of EntityManager are with the World list at the top
# Once you reload, the mobs will disappear rather quickly, but not immediately
###
  mobs:
    creeper: false 
    skeleton: false
    spider: false
    zombie: false
    slime: false
    ghast: false
    pig_zombie: false
    enderman: false
    cave_spider: false
    silverfish: false
    blaze: false
    magma_cube: false
    pig: false
    sheep: false
    cow: false
    chicken: false
    squid: false
    wolf: false
    mushroom_cow: false
    snowman: false
    ocelot: false
    ender_dragon: false
    villager: false
    iron_golem: false

