# EntityManager Configuration v2.9.2 Beta
# Put name of the worlds you want the plugin to work in, aka multiworld support.
# Eggs that are disabled can only be used by players with permission.
# You can charge players for each egg they use, even for monsters or animals
# You can take the egg the player has if they try but fail to use it (stops alert spam)
# You can block the dispense of: SpawnerEggs, Fireballs, XpBottles, and chicken eggs!
# You can block the throwing of Fireballs, XpBottles, and chicken eggs as well
# You can totally disable the spawning of any mob at the end of the config file
# For help, visit : http://dev.bukkit.org/server-mods/entitymanager/pages/
# ************************************************************************************** #
World:
  Worldname:
  - world
  - world_nether 
  - world_end
Economy:
  charge:
    monster: 15
    animal: 5
    other: 10
Disable:
  Experience: false
  Enchanting: false
block:
  zombie-door-break: false
  ender-pickup: true
  player-damage: false
  mob-damage: false
  suffocation-damage: false
  explosion-damage: false
  creeper-explosion: false
  fireball-explosion: false
  fall-damage: false
  splash-potions: false
  arrows: false
  Dispense:
    SpawnerEggs: true
    ChickenEggs: true
    FireBalls: true
    XpBottles: true
  Throw:
    XpBottles: true
    FireCharges: true
    ChickenEggs: false
    EnderPearls: false
    EnderEyes: false
  Entities:
    Boats: false
    Minecarts: false
  Creation-of:
    portals: false
disabled:
  eggs:
    creeper: true
    skeleton: true
    spider: true
    zombie: true
    slime: true
    ghast: true
    pigman: true
    enderman: true
    cavespider: true
    silverfish: true
    blaze: true
    magmacube: true
    pig: false
    sheep: false
    cow: false
    chicken: false
    squid: true
    wolf: false
    mooshroom: false
    ocelot: false
    villager: true
  mobs:
    creeper: false 
    skeleton: false
    spider: false
    zombie: false
    slime: false
    ghast: false
    pigman: false
    enderman: false
    cavespider: false
    silverfish: false
    blaze: false
    magmacube: false
    pig: false
    sheep: false
    cow: false
    chicken: false
    squid: false
    wolf: false
    mooshroom: false
    ocelot: false
    villager: false

