# EntityManager Configuration v3.4
# Put name of the worlds you want the plugin to work in, aka multiworld support.
# Logging is when a player is blocked from doing something, it logs to console
# Send-alerts sends in game alerts to admins when someone fails to do something
# Metrics is a statistics feature, you can disable if you don't want to help me.. :P
# Eggs that are disabled can only be used by players with permission.
# When you have perms and you login, you get a message, you can disable it..
# You can charge players for each egg they use, even for monsters or animals
# All actions that are disabled can be overridden with permission
# You can take the egg the player has if they try but fail to use it (stops alert spam)
# You can block the dispense of: SpawnerEggs, Fireballs, XpBottles, and chicken eggs!
# You can block the throwing of Fireballs, XpBottles, and chicken eggs as well
# You can totally disable the spawning of any mob at the end of the config file
# If a player isn't allowed to drop items you can kick them if they try to drop too many (if they keep spamming the drop button, or if they use hacks to drop items)
# For help, visit : http://dev.bukkit.org/server-mods/entitymanager/pages/
# ************************************************************************************** #
EntityManager:
  Login-MOTD: true
  Send-Alerts: true
  Metrics: true
  Logging: true
  TooManyDrops:
    Kick: true

World:
  Worldname:
  - world
  - world_nether 
  - world_end

Disable:
  Experience: false
  Enchanting: false

block:
  Actions:
    zombie-door-break: false
    ender-pickup: true
    pvp: false
    mob-damage: false
    fishing: false
    arrows: false
  Dispense:
    SpawnerEggs: true
    ChickenEggs: true
    FireBalls: true
    XpBottles: true
    Potions: true
    Items:
    - 7
    - 57
  Throw:
    XpBottles: true
    FireCharges: true
    ChickenEggs: false
    EnderPearls: false
    EnderEyes: false
    Potions: false
  Entities:
    Boats: false
    Minecarts: false
    Paintings: false
  ItemDrop:
    Creative-mode: true
    Survival-mode: false
    On-Death: false
    Block-destroy: false
    Blacklisted-items:
    - 57
  Creation-of:
    portals: false


Economy:
  charge:
    monster: 15
    animal: 5
    npc: 10

disabled:
  eggs:
    creeper: true
    skeleton: true
    spider: true
    zombie: true
    slime: true
    ghast: true
    pigman: true
    enderman: true
    cavespider: true
    silverfish: true
    blaze: true
    magmacube: true
    pig: false
    sheep: false
    cow: false
    chicken: false
    squid: true
    wolf: false
    mooshroom: false
    ocelot: false
    villager: true
  mobs:
    creeper: false 
    skeleton: false
    spider: false
    zombie: false
    slime: false
    ghast: false
    pig_zombie: false
    enderman: false
    cave_spider: false
    silverfish: false
    blaze: false
    magma_cube: false
    pig: false
    sheep: false
    cow: false
    chicken: false
    squid: false
    wolf: false
    mushroom_cow: false
    snowman: false
    ocelot: false
    ender_dragon: false
    villager: false
    iron_golem: false

