#  EntityManager Configuration 3.7
#  http://dev.bukkit.org/server-mods/entitymanager/pages/configuration/
#  For help on the configuration go to the url above.
EntityManager:
  Login-MOTD: true
  Send-Alerts: true
  Metrics: true
  Logging: true
  Advanced-Mob-Remover: false
World:
  All: true
  Worlds:
  - world
  - world_nether
  - world_end
Disable:
  Experience: false
  Enchanting: false
block:
  Actions:
    zombie-door-break: false
    ender-pickup: false
    pvp: false
    mob-damage: false
    fishing: false
    arrows: false
    crop-damage: false
  Dispense:
    SpawnerEggs: true
    ChickenEggs: true
    FireBalls: true
    XpBottles: true
    Potions: true
    Water-Blocks: true
    Lava-Blocks: true
    Items:
    - 7
    - 57
  Throw:
    XpBottles: true
    FireCharges: true
    ChickenEggs: false
    EnderPearls: false
    EnderEyes: false
    Potions: false
  Entities:
    Boats: false
    Minecarts: false
    Paintings: false
  ItemDrop:
    Creative-mode: true
    Survival-mode: false
    Block-destroy: false
    Blacklisted-items:
    - 57
  Place:
    Dragon-Eggs: true
    Ender-Chests: true
    Trip-Wires: false
  Creation-of:
    portals: false
Explosions:
  Level: 0
WorldManager:
  Always: night
  Worlds:
  - add_a_world_u_always_want_to_be_night_or_whatever_you_pick
  - add_a_world_u_always_want_to_be_night_or_whatever_you_pick
Economy:
  charge:
    monster: 15
    animal: 5
    npc: 10
disabled:
  eggs:
    creeper: true
    skeleton: true
    spider: true
    zombie: true
    slime: true
    ghast: true
    pigman: true
    enderman: true
    cavespider: true
    silverfish: true
    blaze: true
    magmacube: true
    pig: false
    sheep: false
    cow: false
    chicken: false
    squid: true
    wolf: false
    mooshroom: false
    ocelot: false
    villager: true
  mobs:
    creeper: false 
    skeleton: false
    spider: false
    zombie: false
    slime: false
    ghast: false
    pig_zombie: false
    enderman: false
    cave_spider: false
    silverfish: false
    blaze: false
    magma_cube: false
    pig: false
    sheep: false
    cow: false
    chicken: false
    squid: false
    wolf: false
    mushroom_cow: false
    snowman: false
    ocelot: false
    ender_dragon: false
    villager: false
    iron_golem: false


