name: EntityManager
author: milkywayz 
main: net.milkycraft.Spawnegg
description: Creatively manage entities
website: http://milkycraft.net
version: 2.8

commands:
    entitymanager:
      aliases: em

  